<a href="https://colab.research.google.com/github/Mgobeaalcoba/Deepnote_Repository/blob/main/Dimensiones_escalara%2C_vector%2C_matriz_o_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
escalar = 5.679
vector = np.array([1,2,3])
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])

In [8]:
print(escalar)
print("\n")
print(vector)
print("\n")
print(matriz)
print("\n")
print(tensor)

5.679


[1 2 3]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [9]:
# print(escalar.shape) Un escalar no tiene atributo shape. Es decir no tiene dimensiones ya que está compuesto por un único numero
print(vector.shape)
print(matriz.shape)
print(tensor.shape)

(3,)
(3, 3)
(3, 3, 3)


In [12]:
len(tensor) # Solo nos indica la cantidad de conjuntos primarios. No las dimensiones detalladas como el shape. Por lo que conviene el shape para medir vectores, matrices y tensores

3

In [14]:
print(tensor.size) # Nos mide la cantidad total de escalares que componen el vector, matriz o tensor. Esta muy bueno! 
print("\n")
print(matriz.size)

27


9
