<a href="https://colab.research.google.com/github/Mgobeaalcoba/Deepnote_Repository/blob/main/matriz_diagonal_y_matriz_simetrica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Matrices especiales: Matriz identidad (con 1111 en su diagonal principal. Matriz inversa: Es la matriz elevada a la -1. Si una matriz la multiplico por su inversa, obtengo la matriz identidad. Matriz Singular: Aquella tal que no existe su inversa. Ahora veamos las matrices diagonales y simetricas**

In [1]:
import numpy as np

In [3]:
vector = np.array([1,2,3,4,5])

matriz = np.diag(vector)

print(matriz)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


Es una matriz con todos elementos distintos de 0 en la diagonal y 0 fuera de ella. No solo pueden ser cuadradas. Veamos ejemplos

In [5]:
print(matriz[0:4,0:3]) # Recorto las 4 primeras filas y las 3 primeras columnas

[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]


Es diagonal pero no cuadrada

In [6]:
print(matriz[0:3,0:4]) # Recorte inverso al anterior. 3 filas y 4 columnas

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


Tmb es diagonal. 
Propiedad importante de las matrices diagonales: 
Cuando multiplico una diagonal por un vector no está haciendo realmente una combinación lineal de las distintas coordenadas. 

In [9]:
A = np.diag([2,3,4,5])
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [18]:
v1 = np.array([[1,1,1,1]]) # Vector columna

In [19]:
print(v1)

[[1 1 1 1]]


In [20]:
print(A.dot(v1.T)) # Traspongo v1 porque sino no puedo hacer el producto

[[2]
 [3]
 [4]
 [5]]


No hubo combinación lineal y solo nos quedaron amplificados los componentes del vector columna. 
¿Como calculo su inversa? 
Sería dividir los elementos de mi vector por el elemento que estoy multiplicando.

In [29]:
A_inv = np.diag([1/2,1/3,1/4,1/5]) # Esta seria la inversa de A
print(A_inv)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


¿Como podemos probar que es la inversa? Hagamos el producto interno de A por su inversa y nos debería arrojar la identidad

In [27]:
identidad = A.dot(A_inv)
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Es la inversa y matematicamente tiene sus beneficios

In [28]:
A_inv_calc = np.linalg.inv(A)
print(A_inv_calc)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


Veamos ahora que es una matriz simétrica: 
Es cuando la matriz es igual a su matriz traspuesta. Que es la matriz traspuesta? Es la misma matriz con sus filas y columnas invertidad. Entonces cualquier matriz diagonal es simétrica, porque tiene todos 0 debajos y todos 0 arriba de su diagonal principal

In [31]:
print(A.T)
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]
[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


Son simetricas

In [33]:
# Veamos un ejemplo de simetria en matrices no diagonales

simetrica = np.array([[1,2,3],
                      [2,-1,7],
                      [3,7,11]])

print(simetrica)
print(simetrica.T)
print(simetrica == simetrica.T)

[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]
[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Es simetrica entonces tmb.