<a href="https://colab.research.google.com/github/Mgobeaalcoba/Deepnote_Repository/blob/main/matrices_ortogonales_y_sus_propiedades.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Una matriz es ortogonal cuando todas sus filas son mutuamente ortonormales y todos sus columnas son mutuamente ortonormales. 

In [1]:
import numpy as np

In [3]:
matriz = np.array([[1,0,0],
                   [0,1,0],
                   [0,0,1]
                   ])
print(matriz)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [7]:
# Veamos que sea ortogonal. Para ello debemos ver que sus columnas sean ortogonales
# y que la norma de ellas sea 1 (es decir que sea ortonormales)

print(matriz[:,0]) # Me quedo con la primer columna
print(matriz[:,0].dot(matriz[:,1])) # Producto entre la primer y la segunda columna
# Acá veo que v1 es ortogonal a v2 si me da 0 el producto interno

[1 0 0]
0


In [13]:
# Verificaciones de producto 0 entre vectores de la matriz

print(matriz[:,0].dot(matriz[:,1]))
print(matriz[:,0].dot(matriz[:,2]))
print(matriz[:,1].dot(matriz[:,2]))
# Las tres comprobaciones que debo hacer en una matriz de 3x3 en columnas
print(matriz[0,:].dot(matriz[1,:]))
print(matriz[0,:].dot(matriz[2,:]))
print(matriz[1,:].dot(matriz[2,:]))
# Las tres comprobaciones que debo hacer en una matriz de 3x3 en filas

0
0
0
0
0
0


In [14]:
# Verificaciones de norma 1 en cada columna o fila de la matriz

# Comprobaciones de columnas
print(np.linalg.norm(matriz[:,0])) # Verifico norma de la 1° columna
print(np.linalg.norm(matriz[:,1])) # Verifico norma de la 2° columna
print(np.linalg.norm(matriz[:,2])) # Verifico norma de la 3° columna
# Comprobaciones de filas
print(np.linalg.norm(matriz[0,:])) # Verifico norma de la 1° fila
print(np.linalg.norm(matriz[1,:])) # Verifico norma de la 2° fila
print(np.linalg.norm(matriz[2,:])) # Verifico norma de la 3° fila

1.0
1.0
1.0
1.0
1.0
1.0


Por lo tanto podemos asegurar que todos los vectores son ortonormales tanto en filas como en columnas. Por lo que la matriz analizada es ortogonal. No existe la definicion de matriz ortonormal.

Propiedades de la matriz ortogonal:
A traspuesta por A es igual a A por A traspuesta y a su vez es igual a la identidad
A traspuesta es igual a la inversa de A
¿Como generamos matrices ortogonales en python? 

In [15]:
A = np.array([[np.cos(100), -np.sin(100)],
              [np.sin(100), np.cos(100)]])
print(A)

[[ 0.86231887  0.50636564]
 [-0.50636564  0.86231887]]


Compruebo que esta matriz sea ortonormal

In [16]:
print(np.linalg.norm(A[:,0]))
print(np.linalg.norm(A[:,1]))
print(np.linalg.norm(A[0,:]))
print(np.linalg.norm(A[1,:]))

0.9999999999999999
0.9999999999999999
0.9999999999999999
0.9999999999999999


Nos devolvió casi 1. Este numero debiera haber sido 1. 

In [20]:
# Ahora veamos que el angulo que forman entre ellos es de 90 grados
# Para ello calculo el producto interno entre ellos y debe dar 0
print(A[:,0].dot(A[:,1])) # Producto de una columna con la otra
print(A[0,:].dot(A[1,:])) # Producto de una fila con la otra

-7.937715190675968e-18
7.937715190675968e-18


In [24]:
print(A[0,:].dot(A[1,:]))
print(A[:,0].dot(A[:,1]))
# Al profesor el dio 0. A mi no porque me da un numero muy cercano a 0. Por eso
# está elevado a la -18

7.937715190675968e-18
-7.937715190675968e-18


In [27]:
A_t = A.T
print(A_t)
print(A_t.dot(A))
print(A.dot(A_t))

[[ 0.86231887 -0.50636564]
 [ 0.50636564  0.86231887]]
[[ 1.00000000e+00 -7.93771519e-18]
 [-7.93771519e-18  1.00000000e+00]]
[[1.00000000e+00 7.93771519e-18]
 [7.93771519e-18 1.00000000e+00]]


Ambas matrices son iguales. Nos devolvió la identidad. No con ceros sino con numeros muy cercanos a 0. Si activaramos la opcion de numpy np.suprese.etc veriamos que es la identidad. 

In [28]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.86231887 -0.50636564]
 [ 0.50636564  0.86231887]]


In [29]:
print(A_t)

[[ 0.86231887 -0.50636564]
 [ 0.50636564  0.86231887]]


Vemos que son iguales

In [30]:
print(1/A_t.dot(A))

[[ 1.00000000e+00 -1.25980837e+17]
 [-1.25980837e+17  1.00000000e+00]]


Ahora tenemos un numero infinitamente grande. Lo que nos hubiera multiplicado el error. Debemos tener mucho cuidado con este tipo de operaciones para no expandir nuestros errores. 