<a href="https://colab.research.google.com/github/Mgobeaalcoba/Deepnote_Repository/blob/main/propiedades_del_producto_interno_de_las_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**El producto interno de matrices es asociativo y distributivo, no es conmutativo.**

**Propiedad asociativa**

---


$$ a * ( b * c ) = ( a * b ) * c $$



**Propiedad distributiva**

---


$$ a * ( b + c ) = ( a * b ) + ( a * c ) $$

**Propiedad commutativa**

---


$$ b * c = c * b $$

In [1]:
import numpy as np

In [4]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,2],[4,2]])

In [5]:
# Asociativa
ABC = A.dot(B.dot(C))
print(ABC)

[[ 60  34]
 [145  82]
 [295 166]]


In [6]:
AB_C = A.dot(B.dot(C))
print(AB_C)

[[ 60  34]
 [145  82]
 [295 166]]


# 1° Conclusión: El producto interno entre matrices es asociativo

In [7]:
# Distributiva
D = A.dot(B+C)
print(D)

[[ 26  19]
 [ 62  46]
 [122  94]]


In [8]:
E = A.dot(B) + A.dot(C)
print(E)

[[ 26  19]
 [ 62  46]
 [122  94]]


In [11]:
print(D==E)

[[ True  True]
 [ True  True]
 [ True  True]]


# 2° Conclusión: El producto interno entre matrices es distributivo

In [9]:
# Conmutativa
F =  B.dot(C)
print(F)

[[15  8]
 [10  6]]


In [12]:
G = C.dot(B)
print(G)

[[ 7 11]
 [ 8 14]]


In [13]:
print(F==G)

[[False False]
 [False False]]


# 3° Conclusión: El producto interno entre matrices no es conmutativo.
**Pero la multiplicación de vectores si es conmutativa**

In [14]:
v1 = np.array([[2],[7]]) # Vector en columnas: 1 cplumna
v2 = np.array([[3],[5]]) # Vector en columnas: 1 columna
v3 = np.array([1,2]) # Vector en filas: 1 fila
print(v1)
print(v2)
print(v3)

[[2]
 [7]]
[[3]
 [5]]
[1 2]


In [16]:
# transpuestos de los vectores
v1_t = v1.T
v2_t = v2.T
v3_t = v3.T
print(v1_t)
print(v2_t)
print(v3_t) # Lo voy a ver igual pero si hago operaciones matematicas notaré la diferencia.

[[2 7]]
[[3 5]]
[1 2]


In [18]:
v1_tv2 = v1_t.dot(v2) # para multiplicar vectores los mismos tienen que estar cruzados. Por eso traspongo
# para tener un vector en fila y uno en columna
v2_tv1 = v2_t.dot(v1)
print(v1_tv2)
print(v2_tv1)
# como se observa el producto interno entre vectores si es conmutativo

[[41]]
[[41]]


In [19]:
# Matrices que pueda multiplicar en un sentido pero no si las transpongo
print(A) # 3 filas y 2 columnas
print(B) # 2 filas y 2 columnas

[[ 2  3]
 [ 5  7]
 [11 13]]
[[1 3]
 [2 1]]


In [20]:
AB = A.dot(B)
print(AB) # Se puede porque coinciden las filas de la primera matriz con las columnas de la segunda

[[ 8  9]
 [19 22]
 [37 46]]


In [23]:
A_t = A.T # 2 filas y 3 columnas
B_t = B.T # 2 filas y 2 columnas
print(A_t)
print(B_t)

[[ 2  5 11]
 [ 3  7 13]]
[[1 2]
 [3 1]]


In [25]:
# A_tB_t = A_t.dot(B_t)
# print(A_tB_t)