<a href="https://colab.research.google.com/github/Mgobeaalcoba/Deepnote_Repository/blob/main/Suma_de_matrices_y_vectores_(broadcasting).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
escalar = 5.679
vector = np.array([3,4,5])
matriz = np.array([[1,2],[3,4],[5,6]])

In [7]:
# A = vector + matriz # no es posible porque el vector tiene 3 columnas y la matriz 2. Para hacerlo debo trasponer o la matriz o el vector
A = vector + matriz.T # Esto es broadcasting. Extender una matriz o un vector para poder hacer operaciones matematicas
print(A)
B = matriz + 42 # Acá Python hace broadcasting tmb
print("\n")
print(B)


[[ 4  7 10]
 [ 5  8 11]]


[[43 44]
 [45 46]
 [47 48]]


In [9]:
C = matriz + np.array([[42],[42],[42]]) # Acá Python hace broadcasting tmb
print(C)

[[43 44]
 [45 46]
 [47 48]]


Broadcasting es entonces extender el elemento de menor dimensión hasta completar o igual el elemento de mayor dimensión. 