<a href="https://colab.research.google.com/github/Mgobeaalcoba/Deepnote_Repository/blob/main/Tipos_especiales_de_matrices_Identidad%2C_inversa%2C_singulares.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
identidad = np.eye(4) # nos devuelve una matriz con todos 1 en la diagonal
# principal y todos 0 fuera de ella. Todos definidos como floats

In [3]:
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
vector = np.array([[2],[3],[5],[7]])
print(vector)

[[2]
 [3]
 [5]
 [7]]


In [6]:
print(identidad.dot(vector)) # Nos devuelve exactamente el mismo vector que teniamos antes

[[2.]
 [3.]
 [5.]
 [7.]]


In [8]:
# print(vector.dot(identidad)) # no puedo hacer el producto de esta forma porque el
# vector tiene 4 filas y 1 columna mientras que identidad tiene 4 filas y 4 columnas.
# Recordemos que para hacer producto de matrices debe coincider la cantidad de columnas
# de la primera matriz con la cantidad de filas de la segunda. 


Entonces la matriz identidad es un elemento neutro. Es como el 1 para los numeros. No cambia nada cuando lo uso para multriplicar. La identidad no transforma ese espacio y eso es super importante

Veamos ahora la inversa de la matriz. 
Por ej la inversa de 5*3 es 15%3

In [9]:
A = np.array([[1,0,1],[0,1,1],[-1,1,1]])

In [10]:
print(A)

[[ 1  0  1]
 [ 0  1  1]
 [-1  1  1]]


Calculemos su inversa

In [11]:
inversa_A = np.linalg.inv(A)

In [12]:
print(inversa_A)

[[ 0.  1. -1.]
 [-1.  2. -1.]
 [ 1. -1.  1.]]


In [13]:
print(A.dot(inversa_A)) # Nos va a devolver la identidad

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Cuando no existe esta identidad la vamos a llamar una matriz singular. Cuando no existe la inversa la llamamos una matriz singular

In [14]:
singular = np.array([[1,1],[1,1]])

In [15]:
print(singular)

[[1 1]
 [1 1]]


In [17]:
# print(np.linalg.inv(singular)) # LinAlgError: Singular matrix No existe la inversa de
# una matriz singular

**No podemos calcular la inversa de una matriz que no sea cuadrada. **

# Tener la inversa nos sirve para hallar x en un sistema de ecuaciones lineales. Veamos como...