<a href="https://colab.research.google.com/github/Mgobeaalcoba/Deepnote_Repository/blob/main/Transposici%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matematicamente hablando trasponer es cambiar las filas por columnas. 
Ej vector fila se convierte en vector columna
matriz de 3x2 se convierte en matriz de 2x3

In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([1,2,3])
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])

para trasponer en Python vamos a usar el metodo ".t" y para guardar como variable una traspuesta vamos a usar el la sintaxis terminada en "_t"

In [10]:
# escalar_t = escalar.t # No se puede trasponer un escalar porque es un dato único
vector_t = vector.T
print(vector_t) # Cuando trasponemos un vector no vamos a ver cambios al imprimir
#Pero si vamos a notar esos cambios si hacemos operaciones matematicas con ella
matriz_t = matriz.T
print("\n")
print(matriz)
print("\n")
print(matriz_t)
tensor_t = tensor.T
print("\n")
print(tensor_t)

[1 2 3]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 4 7]
 [2 5 8]
 [3 6 9]]


[[[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]

 [[ 3 12 21]
  [ 6 15 24]
  [ 9 18 27]]]


In [12]:
matriz_t_t = matriz_t.T # La transpuesta de una matriz transpuesta es la matriz
# original
print(matriz_t_t)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


suma de matriz se puede realizar con matrices de iguales dimensiones. 
Ej: 2x2 + 2x2.
Se suma cada elemento con su par de la segunda matriz y el resultado termina en una tercera matriz en una misma posición

In [14]:
matriz_suma = matriz + matriz_t
print(matriz)
print("\n")
print(matriz_t)
print("\n")
print(matriz_suma)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 4 7]
 [2 5 8]
 [3 6 9]]


[[ 2  6 10]
 [ 6 10 14]
 [10 14 18]]


In [15]:
matriz_mas_escalar = matriz + escalar
print(matriz_mas_escalar)

[[ 6.679  7.679  8.679]
 [ 9.679 10.679 11.679]
 [12.679 13.679 14.679]]


¿Como podemos sumar matrices que no tengan las mismas dimensiones o matrices y vectores?