<a href="https://colab.research.google.com/github/Mgobeaalcoba/Deepnote_Repository/blob/main/transposici%C3%B3n_de_un_producto_de_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Regla de la transposición de un producto de matrices

$$ (a*b)^t = b^t * a^t $$

$$ ((a*b)^t)^t = a*b$$

In [1]:
import numpy as np

In [2]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])

In [3]:
print(A)
print(B)

[[ 2  3]
 [ 5  7]
 [11 13]]
[[1 3]
 [2 1]]


In [4]:
AB_t = A.dot(B).T

In [5]:
B_tA_t = B.T.dot(A.T)

In [6]:
print(AB_t)
print(B_tA_t)

[[ 8 19 37]
 [ 9 22 46]]
[[ 8 19 37]
 [ 9 22 46]]


In [7]:
print(AB_t == B_tA_t)

[[ True  True  True]
 [ True  True  True]]
