<a href="https://colab.research.google.com/github/Mgobeaalcoba/Deepnote_Repository/blob/main/Validad_que_una_matriz_tenga_inversa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Para que un sistema de ecuaciones lineales, necesitamos que la matriz A que representa a este sistema sea cuadrada y que todos sus vectores sean linealmente independientes o sea que no contengan ningun vector ld**

In [1]:
import numpy as np

In [3]:
A = np.array(
[
[0,1,0,0],
[0,0,1,0],
[0,1,1,0],
[1,0,0,1]
])

# Matriz cuadrada pero no todos sus vectores son linealmente independientes

In [4]:
print(A)

[[0 1 0 0]
 [0 0 1 0]
 [0 1 1 0]
 [1 0 0 1]]


Cuando quitemos el vector que es linealmente dependiente la matriz dejará de ser cuadrada :(

Una forma de identifcar cual fila es la que es linealmente dependiente es usar los autovectores y autovalores. ¿Que son?
Una forma de descomponer nuestra matriz:
Ej descomponer 8 en 4x2 o 5+3
En este caso vamos a descomponer nuestra matriz en 3 matrices


In [6]:
lambdas , V = np.linalg.eig(A.T)

print(A[lambdas == 0, :])

[[0 1 1 0]]


Me señala al vector 3 como el dependiente ya que es la suma del vector 1 y el vector 2

Por lo cual si intentamos calcular la inversa de esta matriz nos va a dar que es una matriz singular (no tiene inversa).
De esta forma obtenemos otra manera de caracterizar a una matriz singular como aquella que posee un vector "ld" (linealmente dependiente) dentro de sus filas

In [8]:
# np.linalg.inv(A) # Arroja Error LinAlgError: Singular Matrix

Tmb se puede hacer la misma comprobación de vectores ld viendo las columnas que a la vista no deben ser iguales. Hubiera sido mucho mas facil en este ejemplo. 
No tiene que haber ni filas ni columnas que puedan ser escritos como combinación de otras filas o columnas